// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1iJpg2LttnJypwQRaTOs6q2WBHd3na14',
    appId: '1:692082661577:web:99dad18f5065754100d518',
    messagingSenderId: '692082661577',
    projectId: 'mcq-mentor-6f840',
    authDomain: 'mcq-mentor-6f840.firebaseapp.com',
    storageBucket: 'mcq-mentor-6f840.firebasestorage.app',
    measurementId: 'G-TYKXD8B6E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTSETYgkUFwvqN6Srja-GW4QvlNlaQRBc',
    appId: '1:692082661577:android:3d61943c752e8d1900d518',
    messagingSenderId: '692082661577',
    projectId: 'mcq-mentor-6f840',
    storageBucket: 'mcq-mentor-6f840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgcFUknljq8uKMMJ6Z-_QpEyZsUwjzmsw',
    appId: '1:692082661577:ios:fc1f863439e9e15200d518',
    messagingSenderId: '692082661577',
    projectId: 'mcq-mentor-6f840',
    storageBucket: 'mcq-mentor-6f840.firebasestorage.app',
    iosBundleId: 'com.mcqmentor.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgcFUknljq8uKMMJ6Z-_QpEyZsUwjzmsw',
    appId: '1:692082661577:ios:fc1f863439e9e15200d518',
    messagingSenderId: '692082661577',
    projectId: 'mcq-mentor-6f840',
    storageBucket: 'mcq-mentor-6f840.firebasestorage.app',
    iosBundleId: 'com.mcqmentor.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1iJpg2LttnJypwQRaTOs6q2WBHd3na14',
    appId: '1:692082661577:web:6f87555c1a96b4e200d518',
    messagingSenderId: '692082661577',
    projectId: 'mcq-mentor-6f840',
    authDomain: 'mcq-mentor-6f840.firebaseapp.com',
    storageBucket: 'mcq-mentor-6f840.firebasestorage.app',
    measurementId: 'G-3L4G6E99M2',
  );
}
